export * from './auth.service';
import { AuthService } from './auth.service';
export * from './company.service';
import { CompanyService } from './company.service';
export * from './defect.service';
import { DefectService } from './defect.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './ownerCompany.service';
import { OwnerCompanyService } from './ownerCompany.service';
export * from './ownerCompanyEmployee.service';
import { OwnerCompanyEmployeeService } from './ownerCompanyEmployee.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './sparePart.service';
import { SparePartService } from './sparePart.service';
export * from './tool.service';
import { ToolService } from './tool.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './worksheet.service';
import { WorksheetService } from './worksheet.service';
export * from './worksheetNote.service';
import { WorksheetNoteService } from './worksheetNote.service';
export const APIS = [AuthService, CompanyService, DefectService, HealthService, OwnerCompanyService, OwnerCompanyEmployeeService, RoleService, SparePartService, ToolService, UserService, WorksheetService, WorksheetNoteService];
