/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OwnerCompanyEmployee { 
    id?: number;
    email?: string;
    name?: string;
    telNum?: string;
    title?: string;
    ownerCompanyId?: number;
}

