/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SparePart { 
    id?: number;
    itemName?: string;
    itemNumber?: string;
    nettoBuyingPrice?: number;
    nettoSellingPrice?: number;
    status?: boolean;
}

