/**
 * Service Support API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OwnerCompanyEmployee } from './ownerCompanyEmployee';


export interface Tool {
    id?: number;
    itemNumber?: string;
    name?: string;
    serialNumber?: string;
    typeNumber?: string;
    owner?: OwnerCompanyEmployee;
    /**
     * Az ügyfél neve (kényelmi mező lista nézethez)
     */
    ownerName?: string;
    /**
     * Az ügyfél cégének neve lista nézethez
     */
    ownerCompanyName?: string;
}

