/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Tool { 
    id?: number;
    tool_id?: string;
    itemNumber?: string;
    name?: string;
    serialNumber?: string;
    typeNumber?: string;
    /**
     * Az ügyfél neve (owner_company_employee.name)
     */
    ownerName?: string;
    /**
     * Az ügyfél cégének neve (ha van, különben üresen marad)
     */
    ownerCompanyName?: string;
}

