/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id: number;
    email: string;
    fullName: string;
    phoneNumber?: string;
    position?: string;
    enabled?: boolean;
    roles?: Array<string>;
}

