/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorksheetNote } from './worksheetNote';
import { WorksheetSaveRequestSparePartsInner } from './worksheetSaveRequestSparePartsInner';


export interface WorksheetSaveRequest { 
    toolId: number;
    defectIds: Array<number>;
    notes: Array<WorksheetNote>;
    isWarranty: boolean;
    hasWarrantyCard: boolean;
    hasInvoiceCopy: boolean;
    hasRegistrationProof: boolean;
    assignee?: number;
    status: WorksheetSaveRequest.StatusEnum;
    spareParts: Array<WorksheetSaveRequestSparePartsInner>;
}
export namespace WorksheetSaveRequest {
    export const StatusEnum = {
        Beerkezett: 'BEERKEZETT',
        Folyamatban: 'FOLYAMATBAN',
        Felkuldve: 'FELKULDVE',
        Visszaerkezett: 'VISSZAERKEZETT',
        Kiajanlott: 'KIAJANLOTT',
        Elfogadva: 'ELFOGADVA',
        Kiertestve: 'KIERTESTVE',
        Lezart: 'LEZART'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


