/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorksheetNote } from './worksheetNote';


export interface WorksheetCreateRequest { 
    notes: Array<WorksheetNote>;
    /**
     * A hibák azonosítói
     */
    defectIds?: Array<number>;
    /**
     * A gép azonosítója
     */
    toolId: number;
    /**
     * Garanciális-e
     */
    isWarranty: boolean;
    /**
     * Van-e jótállási kártya
     */
    hasWarrantyCard: boolean;
    /**
     * Van-e számlamásolat
     */
    hasInvoiceCopy: boolean;
    /**
     * Van-e regisztrációs igazolás
     */
    hasRegistrationProof: boolean;
    /**
     * Tulajdonos által megadott leírás
     */
    ownerDescription?: string;
    /**
     * A hozzárendelt szerelő ID-je
     */
    assignee: number;
    /**
     * Munkalap státusza
     */
    status: WorksheetCreateRequest.StatusEnum;
}
export namespace WorksheetCreateRequest {
    export const StatusEnum = {
        Beerkezett: 'BEERKEZETT',
        Folyamatban: 'FOLYAMATBAN',
        Felkuldve: 'FELKULDVE',
        Visszaerkezett: 'VISSZAERKEZETT',
        Kiajanlott: 'KIAJANLOTT',
        Elfogadva: 'ELFOGADVA',
        Kiertestve: 'KIERTESTVE',
        Lezart: 'LEZART'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


