/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorksheetNote { 
    noteId?: number;
    userId?: number;
    noteText?: string;
    userName?: string;
    postedDate?: string;
}

