/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A munkalap státusza
 */
export const WorksheetStatus = {
    Beerkezett: 'BEERKEZETT',
    Folyamatban: 'FOLYAMATBAN',
    Felkuldve: 'FELKULDVE',
    Visszaerkezett: 'VISSZAERKEZETT',
    Kiajanlott: 'KIAJANLOTT',
    Elfogadva: 'ELFOGADVA',
    Kiertestve: 'KIERTESTVE',
    Lezart: 'LEZART'
} as const;
export type WorksheetStatus = typeof WorksheetStatus[keyof typeof WorksheetStatus];

