/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorksheetStatus } from './worksheetStatus';


export interface WorksheetListDto { 
    worksheetId?: number;
    customId?: string;
    toolId?: number;
    toolItemNumber?: string;
    toolSerialNumber?: string;
    ownerCompanyName?: string;
    ownerCompanyEmployeeName?: string;
    assignedUserFullName?: string;
    status?: WorksheetStatus;
}
export namespace WorksheetListDto {
}


