/**
 * Service Support API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Worksheet { 
    id?: number;
    toolId: number;
    isWarranty?: boolean;
    hasWarrantyCard?: boolean;
    hasInvoiceCopy?: boolean;
    hasRegistrationProof?: boolean;
    createdAt?: string;
}

